export const CONTINENT = {
  ASIA: "Asia",
  AFRICA: "Africa",
  AMERICA: "America",
  EUROPE: "Europe",
  OCEANIA: "Oceania",
};

export const CONTINENT_KR = {
  Asia: "아시아",
  Africa: "아프리카",
  America: "아메리카",
  Europe: "유럽",
  Oceania: "오세아니아",
};

export const CONTINENT_DETAIL = {
  SOUTH_ASIA: "South Asia",
  EAST_ASIA: "East Asia",
  SOUTHEAST_ASIA: "Southeast Asia",
  NORTH_ASIA: "North Asia",
  WEST_ASIA: "West Asia",
  CENTRAL_ASIA: "Central Asia",
  NORTH_EUROPE: "North Europe",
  WEST_EUROPE: "West Europe",
  EAST_EUROPE: "East Europe",
  SOUTH_EUROPE: "South Europe",
  CENTRAL_EUROPE: "Central Europe",
  NORTH_AMERICA: "North America",
  CENTRAL_AMERICA: "Central America",
  SOUTH_AMERICA: "South America",
  NORTH_AFRICA: "North Africa",
  WEST_AFRICA: "West Africa",
  EAST_AFRICA: "East Africa",
  SOUTH_AFRICA: "South Africa",
  CENTRAL_AFRICA: "Central Africa",
  AUSTRALASIA: "Australasia",
  MELANESIA: "Melanesia",
  MICRONESIA: "Micronesia",
  POLYNESIA: "Polynesia",
};

export const CONTINENT_DETAIL_KR = {
  "South Asia": "남아시아",
  "East Asia": "동아시아",
  "Southeast Asia": "동남아시아",
  "North Asia": "북아시아",
  "West Asia": "서아시아",
  "Central Asia": "중앙 아시아",
  "North Europe": "북유럽",
  "West Europe": "서유럽",
  "East Europe": "동유럽",
  "South Europe": "남유럽",
  "Central Europe": "중앙유럽",
  "North America": "북아메리카",
  "Central America": "중앙아메리카",
  "South America": "남아메리카",
  "North Africa": "북아프리카",
  "West Africa": "서아프리카",
  "East Africa": "동아프리카",
  "South Africa": "남아프리카",
  "Central Africa": "중앙아프리카",
  Australasia: "오스트랄라시아",
  Melanesia: "멜라네시아",
  Micronesia: "미크로네시아",
  Polynesia: "폴리네시아",
};

export const FLAGS = [
  {
    index: 0,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "아프가니스탄",
    name_en: "Afghanistan",
    image: require("../assets/images/Flag_of_Afghanistan.png"),
    capital_kr: "카불",
    capital_en: "Kabul",
    level: 3,
  },
  {
    index: 1,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "알바니아",
    name_en: "Albania",
    image: require("../assets/images/Flag_of_Albania.png"),
    capital_kr: "티라나",
    capital_en: "Tirana",
    level: 4,
  },
  {
    index: 2,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "알제리",
    name_en: "Algeria",
    image: require("../assets/images/Flag_of_Algeria.png"),
    capital_kr: "알제",
    capital_en: "Algiers",
    level: 3,
  },
  {
    index: 3,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "안도라",
    name_en: "Andorra",
    image: require("../assets/images/Flag_of_Andorra.png"),
    capital_kr: "안도라라베야",
    capital_en: "Andorra la Vella",
    level: 3,
  },
  {
    index: 4,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "앙골라",
    name_en: "Angola",
    image: require("../assets/images/Flag_of_Angola.png"),
    capital_kr: "루안다",
    capital_en: "Luanda",
    level: 3,
  },
  {
    index: 5,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "앤티가 바부다",
    name_en: "Antigua and Barbuda",
    image: require("../assets/images/Flag_of_Antigua_and_Barbuda.png"),
    capital_kr: "세인트존스",
    capital_en: "Saint John's",
    level: 3,
  },
  {
    index: 6,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "아르헨티나",
    name_en: "Argentina",
    image: require("../assets/images/Flag_of_Argentina.png"),
    capital_kr: "부에노스아이레스",
    capital_en: "Buenos Aires",
    level: 2,
  },
  {
    index: 7,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아르메니아",
    name_en: "Armenia",
    image: require("../assets/images/Flag_of_Armenia.png"),
    capital_kr: "예레반",
    capital_en: "Yerevan",
    level: 3,
  },
  {
    index: 8,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.AUSTRALASIA,
    name_kr: "오스트레일리아",
    name_en: "Australia",
    image: require("../assets/images/Flag_of_Australia.png"),
    capital_kr: "캔버라",
    capital_en: "Canberra",
    level: 1,
  },
  {
    index: 9,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "오스트리아",
    name_en: "Austria",
    image: require("../assets/images/Flag_of_Austria.png"),
    capital_kr: "비엔나",
    capital_en: "Vienna",
    level: 2,
  },
  {
    index: 10,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아제르바이잔",
    name_en: "Azerbaijan",
    image: require("../assets/images/Flag_of_Azerbaijan.png"),
    capital_kr: "바쿠",
    capital_en: "Baku",
    level: 3,
  },
  {
    index: 11,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "바레인",
    name_en: "Bahrain",
    image: require("../assets/images/Flag_of_Bahrain.png"),
    capital_kr: "마나마",
    capital_en: "Manama",
    level: 2,
  },
  {
    index: 12,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "방글라데시",
    name_en: "Bangladesh",
    image: require("../assets/images/Flag_of_Bangladesh.png"),
    capital_kr: "다카",
    capital_en: "Dhaka",
    level: 2,
  },
  {
    index: 13,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "바베이도스",
    name_en: "Barbados",
    image: require("../assets/images/Flag_of_Barbados.png"),
    capital_kr: "브리지타운",
    capital_en: "Bridgetown",
    level: 3,
  },
  {
    index: 14,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "벨라루스",
    name_en: "Belarus",
    image: require("../assets/images/Flag_of_Belarus.png"),
    capital_kr: "민스크",
    capital_en: "Minsk",
    level: 3,
  },
  {
    index: 15,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "벨기에",
    name_en: "Belgium",
    image: require("../assets/images/Flag_of_Belgium.png"),
    capital_kr: "브뤼셀",
    capital_en: "Brussels",
    level: 1,
  },
  {
    index: 16,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "벨리즈",
    name_en: "Belize",
    image: require("../assets/images/Flag_of_Belize.png"),
    capital_kr: "벨모판",
    capital_en: "Belmopan",
    level: 3,
  },
  {
    index: 17,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "베냉",
    name_en: "Benin",
    image: require("../assets/images/Flag_of_Benin.png"),
    capital_kr: "포르토노보",
    capital_en: "Porto-Novo",
    level: 2,
  },
  {
    index: 18,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "부탄",
    name_en: "Bhutan",
    image: require("../assets/images/Flag_of_Bhutan.png"),
    capital_kr: "팀부",
    capital_en: "Thimphu",
    level: 3,
  },
  {
    index: 19,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "볼리비아",
    name_en: "Bolivia",
    image: require("../assets/images/Flag_of_Bolivia.png"),
    capital_kr: "라파스",
    capital_en: "La Paz",
    level: 2,
  },
  {
    index: 20,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "보스니아 헤르체고비나",
    name_en: "Bosnia and Herzegovina",
    image: require("../assets/images/Flag_of_Bosnia_and_Herzegovina.png"),
    capital_kr: "사라예보",
    capital_en: "Sarajevo",
    level: 4,
  },
  {
    index: 21,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "보츠와나",
    name_en: "Botswana",
    image: require("../assets/images/Flag_of_Botswana.png"),
    capital_kr: "가보로네",
    capital_en: "Gaborone",
    level: 2,
  },
  {
    index: 22,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "브라질",
    name_en: "Brazil",
    image: require("../assets/images/Flag_of_Brazil.png"),
    capital_kr: "브라질리아",
    capital_en: "Brasilia",
    level: 1,
  },
  {
    index: 23,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "브루나이",
    name_en: "Brunei",
    image: require("../assets/images/Flag_of_Brunei.png"),
    capital_kr: "반다르스리브가완",
    capital_en: "Bandar Seri Begawan",
    level: 4,
  },
  {
    index: 24,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "불가리아",
    name_en: "Bulgaria",
    image: require("../assets/images/Flag_of_Bulgaria.png"),
    capital_kr: "소피아",
    capital_en: "Sofia",
    level: 2,
  },
  {
    index: 25,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "부르키나파소",
    name_en: "Burkina Faso",
    image: require("../assets/images/Flag_of_Burkina_Faso.png"),
    capital_kr: "와가두구",
    capital_en: "Ouagadougou",
    level: 2,
  },
  {
    index: 26,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "부룬디",
    name_en: "Burundi",
    image: require("../assets/images/Flag_of_Burundi.png"),
    capital_kr: "기테가",
    capital_en: "Gitega",
    level: 3,
  },
  {
    index: 27,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "캄보디아",
    name_en: "Cambodia",
    image: require("../assets/images/Flag_of_Cambodia.png"),
    capital_kr: "프놈펜",
    capital_en: "Phnom Penh",
    level: 2,
  },
  {
    index: 28,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "카메룬",
    name_en: "Cameroon",
    image: require("../assets/images/Flag_of_Cameroon.png"),
    capital_kr: "야운데",
    capital_en: "Yaunde",
    level: 2,
  },
  {
    index: 29,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "캐나다",
    name_en: "Canada",
    image: require("../assets/images/Flag_of_Canada.png"),
    capital_kr: "오타와",
    capital_en: "Ottawa",
    level: 1,
  },
  {
    index: 30,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "카보베르데",
    name_en: "Cape Verde",
    image: require("../assets/images/Flag_of_Cape_Verde.png"),
    capital_kr: "프라이아",
    capital_en: "Praia",
    level: 4,
  },
  {
    index: 31,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "차드",
    name_en: "Chad",
    image: require("../assets/images/Flag_of_Chad.png"),
    capital_kr: "은자메나",
    capital_en: "N'Djamena",
    level: 4,
  },
  {
    index: 32,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "칠레",
    name_en: "Chile",
    image: require("../assets/images/Flag_of_Chile.png"),
    capital_kr: "산티아고",
    capital_en: "Santiago",
    level: 2,
  },
  {
    index: 33,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "콜롬비아",
    name_en: "Colombia",
    image: require("../assets/images/Flag_of_Colombia.png"),
    capital_kr: "보고타",
    capital_en: "Bogota",
    level: 3,
  },
  {
    index: 34,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "코스타리카",
    name_en: "Costarica",
    image: require("../assets/images/Flag_of_Costarica.png"),
    capital_kr: "산호세",
    capital_en: "San Jose",
    level: 3,
  },
  {
    index: 35,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "코트디부아르",
    name_en: "Côte_d'Ivoire",
    image: require("../assets/images/Flag_of_CotedIvoire.png"),
    capital_kr: "야무수크로",
    capital_en: "Yamoussoukro",
    level: 2,
  },
  {
    index: 36,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "크로아티아",
    name_en: "Croatia",
    image: require("../assets/images/Flag_of_Croatia.png"),
    capital_kr: "자그레브",
    capital_en: "Zagreb",
    level: 4,
  },
  {
    index: 37,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "쿠바",
    name_en: "Cuba",
    image: require("../assets/images/Flag_of_Cuba.png"),
    capital_kr: "하바나",
    capital_en: "Havana",
    level: 2,
  },
  {
    index: 38,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "키프로스",
    name_en: "Cyprus",
    image: require("../assets/images/Flag_of_Cyprus.png"),
    capital_kr: "니코시아",
    capital_en: "Nicosia",
    level: 4,
  },
  {
    index: 39,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "덴마크",
    name_en: "Denmark",
    image: require("../assets/images/Flag_of_Denmark.png"),
    capital_kr: "코펜하겐",
    capital_en: "Copenhagen",
    level: 1,
  },
  {
    index: 40,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "지부티",
    name_en: "Djibouti",
    image: require("../assets/images/Flag_of_Djibouti.png"),
    capital_kr: "지부티",
    capital_en: "Djibouti",
    level: 2,
  },
  {
    index: 41,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "도미니카 연방",
    name_en: "Dominica",
    image: require("../assets/images/Flag_of_Dominica.png"),
    capital_kr: "로조",
    capital_en: "Roseau",
    level: 4,
  },
  {
    index: 42,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "동티모르",
    name_en: "East Timor",
    image: require("../assets/images/Flag_of_East_Timor.png"),
    capital_kr: "딜리",
    capital_en: "Dili",
    level: 2,
  },
  {
    index: 43,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "에콰도르",
    name_en: "Ecuador",
    image: require("../assets/images/Flag_of_Ecuador.png"),
    capital_kr: "키토",
    capital_en: "Quito",
    level: 2,
  },
  {
    index: 44,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "이집트",
    name_en: "Egypt",
    image: require("../assets/images/Flag_of_Egypt.png"),
    capital_kr: "카이로",
    capital_en: "Cairo",
    level: 1,
  },
  {
    index: 45,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "엘살바도르",
    name_en: "El Salvador",
    image: require("../assets/images/Flag_of_El_Salvador.png"),
    capital_kr: "산살바도르",
    capital_en: "San Salvador",
    level: 2,
  },
  {
    index: 46,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "잉글랜드",
    name_en: "England",
    image: require("../assets/images/Flag_of_England.png"),
    capital_kr: "런던",
    capital_en: "London",
    level: 1,
  },
  {
    index: 47,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "적도 기니",
    name_en: "Equatorial Guinea",
    image: require("../assets/images/Flag_of_Equatorial_Guinea.png"),
    capital_kr: "말라보",
    capital_en: "Malabo",
    level: 4,
  },
  {
    index: 48,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "에리트레아",
    name_en: "Eritrea",
    image: require("../assets/images/Flag_of_Eritrea.png"),
    capital_kr: "아스마라",
    capital_en: "Asmara",
    level: 3,
  },
  {
    index: 49,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "에스토니아",
    name_en: "Estonia",
    image: require("../assets/images/Flag_of_Estonia.png"),
    capital_kr: "탈린",
    capital_en: "Tallinn",
    level: 3,
  },
  {
    index: 50,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "에스와티니",
    name_en: "Eswatini",
    image: require("../assets/images/Flag_of_Eswatini.png"),
    capital_kr: "음바바네",
    capital_en: "Mbabane",
    level: 4,
  },
  {
    index: 51,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "에티오피아",
    name_en: "Ethiopia",
    image: require("../assets/images/Flag_of_Ethiopia.png"),
    capital_kr: "아디스아바바",
    capital_en: "Addis Ababa",
    level: 4,
  },
  {
    index: 52,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "피지",
    name_en: "Fiji",
    image: require("../assets/images/Flag_of_Fiji.png"),
    capital_kr: "수바",
    capital_en: "Suva",
    level: 4,
  },
  {
    index: 53,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "핀란드",
    name_en: "Finland",
    image: require("../assets/images/Flag_of_Finland.png"),
    capital_kr: "헬싱키",
    capital_en: "Helsinki",
    level: 2,
  },
  {
    index: 54,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "프랑스",
    name_en: "France",
    image: require("../assets/images/Flag_of_France.png"),
    capital_kr: "파리",
    capital_en: "Paris",
    level: 1,
  },
  {
    index: 55,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "가봉",
    name_en: "Gabon",
    image: require("../assets/images/Flag_of_Gabon.png"),
    capital_kr: "리브르빌",
    capital_en: "Libreville",
    level: 2,
  },
  {
    index: 56,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "조지아",
    name_en: "Georgia",
    image: require("../assets/images/Flag_of_Georgia.png"),
    capital_kr: "트빌리시",
    capital_en: "Tbilisi",
    level: 4,
  },
  {
    index: 57,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "독일",
    name_en: "Germany",
    image: require("../assets/images/Flag_of_Germany.png"),
    capital_kr: "베를린",
    capital_en: "Berlin",
    level: 1,
  },
  {
    index: 58,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "가나",
    name_en: "Ghana",
    image: require("../assets/images/Flag_of_Ghana.png"),
    capital_kr: "아크라",
    capital_en: "Accra",
    level: 2,
  },
  {
    index: 59,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "그리스",
    name_en: "Greece",
    image: require("../assets/images/Flag_of_Greece.png"),
    capital_kr: "아테네",
    capital_en: "Athens",
    level: 1,
  },
  {
    index: 60,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "그레나다",
    name_en: "Grenada",
    image: require("../assets/images/Flag_of_Grenada.png"),
    capital_kr: "세인트조지스",
    capital_en: "Saint George's",
    level: 4,
  },
  {
    index: 61,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "과테말라",
    name_en: "Guatemala",
    image: require("../assets/images/Flag_of_Guatemala.png"),
    capital_kr: "과테말라시티",
    capital_en: "Guatemala City",
    level: 2,
  },
  {
    index: 62,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "기니비사우",
    name_en: "Guinea Bissau",
    image: require("../assets/images/Flag_of_Guinea-Bissau.png"),
    capital_kr: "비사우",
    capital_en: "Bissau",
    level: 4,
  },
  {
    index: 63,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "기니",
    name_en: "Guinea",
    image: require("../assets/images/Flag_of_Guinea.png"),
    capital_kr: "코나크리",
    capital_en: "Conakry",
    level: 2,
  },
  {
    index: 64,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "가이아나",
    name_en: "Guyana",
    image: require("../assets/images/Flag_of_Guyana.png"),
    capital_kr: "조지타운",
    capital_en: "Georgetown",
    level: 4,
  },
  {
    index: 65,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "아이티",
    name_en: "Haiti",
    image: require("../assets/images/Flag_of_Haiti.png"),
    capital_kr: "포르토프랭스",
    capital_en: "Port-au-Prince",
    level: 4,
  },
  {
    index: 66,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "온두라스",
    name_en: "Honduras",
    image: require("../assets/images/Flag_of_Honduras.png"),
    capital_kr: "테구시갈파",
    capital_en: "Tegucigalpa",
    level: 3,
  },
  {
    index: 67,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "홍콩",
    name_en: "Hong Kong",
    image: require("../assets/images/Flag_of_Hong_Kong.png"),
    capital_kr: "없음",
    capital_en: "Nothing",
    level: 2,
  },
  {
    index: 68,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "헝가리",
    name_en: "Hungary",
    image: require("../assets/images/Flag_of_Hungary.png"),
    capital_kr: "부다페스트",
    capital_en: "Budapest",
    level: 2,
  },
  {
    index: 69,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "아이슬란드",
    name_en: "Iceland",
    image: require("../assets/images/Flag_of_Iceland.png"),
    capital_kr: "레이캬비크",
    capital_en: "Reykjavik",
    level: 2,
  },
  {
    index: 70,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "인도",
    name_en: "India",
    image: require("../assets/images/Flag_of_India.png"),
    capital_kr: "뉴델리",
    capital_en: "New Delhi",
    level: 2,
  },
  {
    index: 71,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "인도네시아",
    name_en: "Indonesia",
    image: require("../assets/images/Flag_of_Indonesia.png"),
    capital_kr: "자카르타",
    capital_en: "Jakarta",
    level: 1,
  },
  {
    index: 72,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이란",
    name_en: "Iran",
    image: require("../assets/images/Flag_of_Iran.png"),
    capital_kr: "테헤란",
    capital_en: "Teheran",
    level: 3,
  },
  {
    index: 73,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이라크",
    name_en: "Iraq",
    image: require("../assets/images/Flag_of_Iraq.png"),
    capital_kr: "바그다드",
    capital_en: "Baghdad",
    level: 2,
  },
  {
    index: 74,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "아일랜드",
    name_en: "Ireland",
    image: require("../assets/images/Flag_of_Ireland.png"),
    capital_kr: "더블린",
    capital_en: "Dublin",
    level: 2,
  },
  {
    index: 75,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이스라엘",
    name_en: "Israel",
    image: require("../assets/images/Flag_of_Israel.png"),
    capital_kr: "예루살렘",
    capital_en: "Jerusalem",
    level: 3,
  },
  {
    index: 76,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "이탈리아",
    name_en: "Italy",
    image: require("../assets/images/Flag_of_Italy.png"),
    capital_kr: "로마",
    capital_en: "Rome",
    level: 1,
  },
  {
    index: 77,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "자메이카",
    name_en: "Jamaica",
    image: require("../assets/images/Flag_of_Jamaica.png"),
    capital_kr: "킹스턴",
    capital_en: "Kingston",
    level: 2,
  },
  {
    index: 78,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "일본",
    name_en: "Japan",
    image: require("../assets/images/Flag_of_Japan.png"),
    capital_kr: "도쿄",
    capital_en: "Tokyo",
    level: 1,
  },
  {
    index: 79,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "요르단",
    name_en: "Jordan",
    image: require("../assets/images/Flag_of_Jordan.png"),
    capital_kr: "암만",
    capital_en: "Amman",
    level: 3,
  },
  {
    index: 80,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "카자흐스탄",
    name_en: "Kazakhstan",
    image: require("../assets/images/Flag_of_Kazakhstan.png"),
    capital_kr: "누르술탄",
    capital_en: "Nur-Sultan",
    level: 4,
  },
  {
    index: 81,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "케냐",
    name_en: "Kenya",
    image: require("../assets/images/Flag_of_Kenya.png"),
    capital_kr: "나이로비",
    capital_en: "Nairobi",
    level: 4,
  },
  {
    index: 82,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "키리바시",
    name_en: "Kiribati",
    image: require("../assets/images/Flag_of_Kiribati.png"),
    capital_kr: "타라와",
    capital_en: "Tarawa",
    level: 4,
  },
  {
    index: 83,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "코소보",
    name_en: "Kosovo",
    image: require("../assets/images/Flag_of_Kosovo.png"),
    capital_kr: "프리슈티나",
    capital_en: "Pristina",
    level: 4,
  },
  {
    index: 84,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "쿠웨이트",
    name_en: "Kuwait",
    image: require("../assets/images/Flag_of_Kuwait.png"),
    capital_kr: "쿠웨이트",
    capital_en: "Kuwait",
    level: 3,
  },
  {
    index: 85,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "키르기스스탄",
    name_en: "Kyrgyzstan",
    image: require("../assets/images/Flag_of_Kyrgyzstan.png"),
    capital_kr: "비슈케크",
    capital_en: "Bishkek",
    level: 4,
  },
  {
    index: 86,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "라오스",
    name_en: "Laos",
    image: require("../assets/images/Flag_of_Laos.png"),
    capital_kr: "비엔티안",
    capital_en: "Vientiane",
    level: 2,
  },
  {
    index: 87,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "라트비아",
    name_en: "Latvia",
    image: require("../assets/images/Flag_of_Latvia.png"),
    capital_kr: "리가",
    capital_en: "Riga",
    level: 2,
  },
  {
    index: 88,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "레바논",
    name_en: "Lebanon",
    image: require("../assets/images/Flag_of_Lebanon.png"),
    capital_kr: "베이루트",
    capital_en: "Beirut",
    level: 4,
  },
  {
    index: 89,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "레소토",
    name_en: "Lesotho",
    image: require("../assets/images/Flag_of_Lesotho.png"),
    capital_kr: "마세루",
    capital_en: "Maseru",
    level: 4,
  },
  {
    index: 90,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "라이베리아",
    name_en: "Liberia",
    image: require("../assets/images/Flag_of_Liberia.png"),
    capital_kr: "몬로비아",
    capital_en: "Monrovia",
    level: 3,
  },
  {
    index: 91,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "리비아",
    name_en: "Libya",
    image: require("../assets/images/Flag_of_Libya.png"),
    capital_kr: "트리폴리",
    capital_en: "Tripoli",
    level: 3,
  },
  {
    index: 92,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "리히텐슈타인",
    name_en: "Liechtenstein",
    image: require("../assets/images/Flag_of_Liechtenstein.png"),
    capital_kr: "파두츠",
    capital_en: "Vaduz",
    level: 3,
  },
  {
    index: 93,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "리투아니아",
    name_en: "Lithuania",
    image: require("../assets/images/Flag_of_Lithuania.png"),
    capital_kr: "빌뉴스",
    capital_en: "Vilnius",
    level: 2,
  },
  {
    index: 94,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "룩셈부르크",
    name_en: "Luxembourg",
    image: require("../assets/images/Flag_of_Luxembourg.png"),
    capital_kr: "룩셈부르크",
    capital_en: "Luxembourg",
    level: 2,
  },
  {
    index: 95,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "마다가스카르",
    name_en: "Madagascar",
    image: require("../assets/images/Flag_of_Madagascar.png"),
    capital_kr: "안타나나리보",
    capital_en: "Antananarivo",
    level: 2,
  },
  {
    index: 96,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "말라위",
    name_en: "Malawi",
    image: require("../assets/images/Flag_of_Malawi.png"),
    capital_kr: "릴롱궤",
    capital_en: "Lilongwe",
    level: 3,
  },
  {
    index: 97,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "말레이시아",
    name_en: "Malaysia",
    image: require("../assets/images/Flag_of_Malaysia.png"),
    capital_kr: "쿠알라룸푸르",
    capital_en: "Kuala Lumpur",
    level: 2,
  },
  {
    index: 98,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "몰디브",
    name_en: "Maldives",
    image: require("../assets/images/Flag_of_Maldives.png"),
    capital_kr: "말레",
    capital_en: "Male",
    level: 4,
  },
  {
    index: 99,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "말리",
    name_en: "Mali",
    image: require("../assets/images/Flag_of_Mali.png"),
    capital_kr: "바마코",
    capital_en: "Bamako",
    level: 2,
  },
  {
    index: 100,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "몰타",
    name_en: "Malta",
    image: require("../assets/images/Flag_of_Malta.png"),
    capital_kr: "발레타",
    capital_en: "Valleta",
    level: 2,
  },
  {
    index: 101,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "모리타니",
    name_en: "Mauritania",
    image: require("../assets/images/Flag_of_Mauritania.png"),
    capital_kr: "누악쇼트",
    capital_en: "Nouakchott",
    level: 4,
  },
  {
    index: 102,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "모리셔스",
    name_en: "Mauritius",
    image: require("../assets/images/Flag_of_Mauritius.png"),
    capital_kr: "포트루이스",
    capital_en: "Port Louis",
    level: 3,
  },
  {
    index: 103,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "멕시코",
    name_en: "Mexico",
    image: require("../assets/images/Flag_of_Mexico.png"),
    capital_kr: "멕시코시티",
    capital_en: "Mexico City",
    level: 1,
  },
  {
    index: 104,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "몰도바",
    name_en: "Moldova",
    image: require("../assets/images/Flag_of_Moldova.png"),
    capital_kr: "키시네프",
    capital_en: "Kishinev",
    level: 3,
  },
  {
    index: 105,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "모나코",
    name_en: "Monaco",
    image: require("../assets/images/Flag_of_Monaco.png"),
    capital_kr: "모나코",
    capital_en: "Monaco",
    level: 2,
  },
  {
    index: 106,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "몽골",
    name_en: "Mongolia",
    image: require("../assets/images/Flag_of_Mongolia.png"),
    capital_kr: "울란바토르",
    capital_en: "Ulaanbaatar",
    level: 4,
  },
  {
    index: 107,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "몬테네그로",
    name_en: "Montenegro",
    image: require("../assets/images/Flag_of_Montenegro.png"),
    capital_kr: "포드고리차",
    capital_en: "Podgorica",
    level: 4,
  },
  {
    index: 108,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "모로코",
    name_en: "Morocco",
    image: require("../assets/images/Flag_of_Morocco.png"),
    capital_kr: "라바트",
    capital_en: "Rabat",
    level: 3,
  },
  {
    index: 109,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "모잠비크",
    name_en: "Mozambique",
    image: require("../assets/images/Flag_of_Mozambique.png"),
    capital_kr: "마푸투",
    capital_en: "Maputo",
    level: 4,
  },
  {
    index: 110,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "미얀마",
    name_en: "Myanmar",
    image: require("../assets/images/Flag_of_Myanmar.png"),
    capital_kr: "네피도",
    capital_en: "Naypyidaw",
    level: 3,
  },
  {
    index: 111,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "나미비아",
    name_en: "Namibia",
    image: require("../assets/images/Flag_of_Namibia.png"),
    capital_kr: "빈트후크",
    capital_en: "Windhoek",
    level: 4,
  },
  {
    index: 112,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "나우루",
    name_en: "Nauru",
    image: require("../assets/images/Flag_of_Nauru.png"),
    capital_kr: "야렌",
    capital_en: "Yaren",
    level: 4,
  },
  {
    index: 113,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "네팔",
    name_en: "Nepal",
    image: require("../assets/images/Flag_of_Nepal.png"),
    capital_kr: "카트만두",
    capital_en: "Kathmandu",
    level: 4,
  },
  {
    index: 114,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.AUSTRALASIA,
    name_kr: "뉴질랜드",
    name_en: "New Zealand",
    image: require("../assets/images/Flag_of_New_Zealand.png"),
    capital_kr: "웰링턴",
    capital_en: "Wellington",
    level: 1,
  },
  {
    index: 115,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "니제르",
    name_en: "Niger",
    image: require("../assets/images/Flag_of_Niger.png"),
    capital_kr: "니아메",
    capital_en: "Niamey",
    level: 3,
  },
  {
    index: 116,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "나이지리아",
    name_en: "Nigeria",
    image: require("../assets/images/Flag_of_Nigeria.png"),
    capital_kr: "아부자",
    capital_en: "Abuja",
    level: 2,
  },
  {
    index: 117,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "조선민주주의인민공화국",
    name_en: "North Korea",
    image: require("../assets/images/Flag_of_North_Korea.png"),
    capital_kr: "평양",
    capital_en: "Pyongyang",
    level: 1,
  },
  {
    index: 118,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "북마케도니아",
    name_en: "North Macedonia",
    image: require("../assets/images/Flag_of_North_Macedonia.png"),
    capital_kr: "스코페",
    capital_en: "Skopje",
    level: 4,
  },
  {
    index: 119,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "노르웨이",
    name_en: "Norway",
    image: require("../assets/images/Flag_of_Norway.png"),
    capital_kr: "오슬로",
    capital_en: "Oslo",
    level: 2,
  },
  {
    index: 120,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "오만",
    name_en: "Oman",
    image: require("../assets/images/Flag_of_Oman.png"),
    capital_kr: "무스카트",
    capital_en: "Muscat",
    level: 4,
  },
  {
    index: 121,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "파키스탄",
    name_en: "Pakistan",
    image: require("../assets/images/Flag_of_Pakistan.png"),
    capital_kr: "이슬라마바드",
    capital_en: "Islamabad",
    level: 2,
  },
  {
    index: 122,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "팔라우",
    name_en: "Palau",
    image: require("../assets/images/Flag_of_Palau.png"),
    capital_kr: "멜레케오크",
    capital_en: "Melekeok",
    level: 1,
  },
  {
    index: 123,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "팔레스타인",
    name_en: "Palestine",
    image: require("../assets/images/Flag_of_Palestine.png"),
    capital_kr: "라말라",
    capital_en: "Ramallah",
    level: 3,
  },
  {
    index: 124,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "파나마",
    name_en: "Panama",
    image: require("../assets/images/Flag_of_Panama.png"),
    capital_kr: "파나마시티",
    capital_en: "Panama City",
    level: 4,
  },
  {
    index: 125,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "파푸아뉴기니",
    name_en: "Papua New Guinea",
    image: require("../assets/images/Flag_of_Papua_New_Guinea.png"),
    capital_kr: "포트모르즈비",
    capital_en: "Port Moresby",
    level: 4,
  },
  {
    index: 126,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "파라과이",
    name_en: "Paraguay",
    image: require("../assets/images/Flag_of_Paraguay.png"),
    capital_kr: "아순시온",
    capital_en: "Asuncion",
    level: 3,
  },
  {
    index: 127,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "페루",
    name_en: "Peru",
    image: require("../assets/images/Flag_of_Peru.png"),
    capital_kr: "리마",
    capital_en: "Lima",
    level: 3,
  },
  {
    index: 128,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "폴란드",
    name_en: "Poland",
    image: require("../assets/images/Flag_of_Poland.png"),
    capital_kr: "바르샤바",
    capital_en: "Warsaw",
    level: 1,
  },
  {
    index: 129,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "포르투갈",
    name_en: "Portugal",
    image: require("../assets/images/Flag_of_Portugal.png"),
    capital_kr: "리스본",
    capital_en: "Lisbon",
    level: 3,
  },
  {
    index: 130,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "카타르",
    name_en: "Qatar",
    image: require("../assets/images/Flag_of_Qatar.png"),
    capital_kr: "도하",
    capital_en: "Doha",
    level: 1,
  },
  {
    index: 131,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "루마니아",
    name_en: "Romania",
    image: require("../assets/images/Flag_of_Romania.png"),
    capital_kr: "부쿠레슈티",
    capital_en: "Bucharest",
    level: 2,
  },
  {
    index: 132,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "러시아",
    name_en: "Russia",
    image: require("../assets/images/Flag_of_Russia.png"),
    capital_kr: "모스크바",
    capital_en: "Moskva",
    level: 2,
  },
  {
    index: 133,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "르완다",
    name_en: "Rwanda",
    image: require("../assets/images/Flag_of_Rwanda.png"),
    capital_kr: "키갈리",
    capital_en: "Kigali",
    level: 3,
  },
  {
    index: 134,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트키츠 네비스",
    name_en: "Saint Kitts and Nevis",
    image: require("../assets/images/Flag_of_Saint_Kitts_and_Nevis.png"),
    capital_kr: "바스테르",
    capital_en: "Basseterre",
    level: 4,
  },
  {
    index: 135,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트루시아",
    name_en: "Saint Kitts and Nevis",
    image: require("../assets/images/Flag_of_Saint_Lucia.png"),
    capital_kr: "캐스트리스",
    capital_en: "Castries",
    level: 2,
  },
  {
    index: 136,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트빈센트 그레나딘",
    name_en: "Saint Vincent and the Grenadines",
    image: require("../assets/images/Flag_of_Saint_Vincent_and_the_Grenadines.png"),
    capital_kr: "킹스타운",
    capital_en: "Kingstown",
    level: 3,
  },
  {
    index: 137,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "사모아",
    name_en: "Samoa",
    image: require("../assets/images/Flag_of_Samoa.png"),
    capital_kr: "아피아",
    capital_en: "Apia",
    level: 2,
  },
  {
    index: 138,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "산마리노",
    name_en: "San Marino",
    image: require("../assets/images/Flag_of_San_Marino.png"),
    capital_kr: "산마리노",
    capital_en: "San Marino",
    level: 4,
  },
  {
    index: 139,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "상투메 프린시페",
    name_en: "Sao Tome and Principe",
    image: require("../assets/images/Flag_of_Sao_Tome_and_Principe.png"),
    capital_kr: "상투메",
    capital_en: "Sao Tome",
    level: 3,
  },
  {
    index: 140,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "사우디아라비아",
    name_en: "Saudi Arabia",
    image: require("../assets/images/Flag_of_Saudi_Arabia.png"),
    capital_kr: "리야드",
    capital_en: "Riyadh",
    level: 2,
  },
  {
    index: 141,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "스코틀랜드",
    name_en: "Scotland",
    image: require("../assets/images/Flag_of_Scotland.png"),
    capital_kr: "에든버러",
    capital_en: "Edinburgh",
    level: 3,
  },
  {
    index: 142,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "세네갈",
    name_en: "Senegal",
    image: require("../assets/images/Flag_of_Senegal.png"),
    capital_kr: "다카르",
    capital_en: "Dakar",
    level: 3,
  },
  {
    index: 143,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "세르비아",
    name_en: "Serbia",
    image: require("../assets/images/Flag_of_Serbia.png"),
    capital_kr: "베오그라드",
    capital_en: "Beograd",
    level: 4,
  },
  {
    index: 144,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "세이셸",
    name_en: "Seychelles",
    image: require("../assets/images/Flag_of_Seychelles.png"),
    capital_kr: "빅토리아",
    capital_en: "Victoria",
    level: 4,
  },
  {
    index: 145,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "시에라리온",
    name_en: "Sierra Leone",
    image: require("../assets/images/Flag_of_Sierra_Leone.png"),
    capital_kr: "프리타운",
    capital_en: "Freetown",
    level: 3,
  },
  {
    index: 146,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "싱가포르",
    name_en: "Singapore",
    image: require("../assets/images/Flag_of_Singapore.png"),
    capital_kr: "싱가포르",
    capital_en: "Singapore",
    level: 2,
  },
  {
    index: 147,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "슬로바키아",
    name_en: "Slovakia",
    image: require("../assets/images/Flag_of_Slovakia.png"),
    capital_kr: "브라티슬라바",
    capital_en: "브라티슬라바",
    level: 3,
  },
  {
    index: 148,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "소말리아",
    name_en: "Somalia",
    image: require("../assets/images/Flag_of_Somalia.png"),
    capital_kr: "모가디슈",
    capital_en: "Mogadishu",
    level: 1,
  },
  {
    index: 149,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "남아프리카 공화국",
    name_en: "South Africa",
    image: require("../assets/images/Flag_of_South_Africa.png"),
    capital_kr: "프리토리아",
    capital_en: "Pretoria",
    level: 4,
  },
  {
    index: 150,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "대한민국",
    name_en: "South Korea",
    image: require("../assets/images/Flag_of_South_Korea.png"),
    capital_kr: "서울",
    capital_en: "Seoul",
    level: 1,
  },
  {
    index: 151,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "남수단",
    name_en: "South Sudan",
    image: require("../assets/images/Flag_of_South_Sudan.png"),
    capital_kr: "주바",
    capital_en: "Juba",
    level: 4,
  },
  {
    index: 152,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "스페인",
    name_en: "Spain",
    image: require("../assets/images/Flag_of_Spain.png"),
    capital_kr: "마드리드",
    capital_en: "Madrid",
    level: 2,
  },
  {
    index: 153,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "스리랑카",
    name_en: "Sri Lanka",
    image: require("../assets/images/Flag_of_Sri_Lanka.png"),
    capital_kr: "콜롬보",
    capital_en: "Colombo",
    level: 4,
  },
  {
    index: 154,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "수단",
    name_en: "Sudan",
    image: require("../assets/images/Flag_of_Sudan.png"),
    capital_kr: "카르툼",
    capital_en: "Khartoum",
    level: 4,
  },
  {
    index: 155,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "수리남",
    name_en: "Suriname",
    image: require("../assets/images/Flag_of_Suriname.png"),
    capital_kr: "파라마리보",
    capital_en: "Paramaribo",
    level: 3,
  },
  {
    index: 156,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "스웨덴",
    name_en: "Sweden",
    image: require("../assets/images/Flag_of_Sweden.png"),
    capital_kr: "스톡홀름",
    capital_en: "Stockholm",
    level: 2,
  },
  {
    index: 157,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "스위스",
    name_en: "Switzerland",
    image: require("../assets/images/Flag_of_Switzerland.png"),
    capital_kr: "베른",
    capital_en: "Bern",
    level: 1,
  },
  {
    index: 158,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "시리아",
    name_en: "Syria",
    image: require("../assets/images/Flag_of_Syria.png"),
    capital_kr: "다마스쿠스",
    capital_en: "DAMASCUS",
    level: 3,
  },
  {
    index: 159,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "타지키스탄",
    name_en: "Tajikistan",
    image: require("../assets/images/Flag_of_Tajikistan.png"),
    capital_kr: "두샨베",
    capital_en: "Dushanbe",
    level: 3,
  },
  {
    index: 160,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "탄자니아",
    name_en: "Tanzania",
    image: require("../assets/images/Flag_of_Tanzania.png"),
    capital_kr: "도도마",
    capital_en: "Dodoma",
    level: 4,
  },
  {
    index: 161,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "태국",
    name_en: "Thailand",
    image: require("../assets/images/Flag_of_Thailand.png"),
    capital_kr: "방콕",
    capital_en: "Bangkok",
    level: 2,
  },
  {
    index: 162,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아시리아",
    name_en: "Assyrians",
    image: require("../assets/images/Flag_of_the_Assyrians.png"),
    capital_kr: "니네베",
    capital_en: "Nineveh",
    level: 4,
  },
  {
    index: 163,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "바하마",
    name_en: "Bahamas",
    image: require("../assets/images/Flag_of_the_Bahamas.png"),
    capital_kr: "나사우",
    capital_en: "Nassau",
    level: 3,
  },
  {
    index: 164,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "중앙아프리카 공화국",
    name_en: "Central African Republic",
    image: require("../assets/images/Flag_of_the_Central_African_Republic.png"),
    capital_kr: "방기",
    capital_en: "Bangui",
    level: 4,
  },
  {
    index: 165,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "코모로",
    name_en: "Comoros",
    image: require("../assets/images/Flag_of_the_Comoros.png"),
    capital_kr: "모로니",
    capital_en: "Moroni",
    level: 4,
  },
  {
    index: 166,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "체코",
    name_en: "Czech Republic",
    image: require("../assets/images/Flag_of_the_Czech_Republic.png"),
    capital_kr: "프라하",
    capital_en: "Praha",
    level: 2,
  },
  {
    index: 167,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "콩고 민주 공화국",
    name_en: "Democratic Republic of the Congo",
    image: require("../assets/images/Flag_of_the_Democratic_Republic_of_the_Congo.png"),
    capital_kr: "킨샤사",
    capital_en: "Kinshasa",
    level: 4,
  },
  {
    index: 168,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "도미니카 공화국",
    name_en: "Dominican Republic",
    image: require("../assets/images/Flag_of_the_Dominican_Republic.png"),
    capital_kr: "산토도밍고",
    capital_en: "Santo Domingo",
    level: 4,
  },
  {
    index: 169,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "미크로네시아 연방",
    name_en: "Federated States of Micronesia",
    image: require("../assets/images/Flag_of_the_Federated_States_of_Micronesia.png"),
    capital_kr: "팔리키르",
    capital_en: "Palikir",
    level: 4,
  },
  {
    index: 170,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "감비아",
    name_en: "Gambia",
    image: require("../assets/images/Flag_of_The_Gambia.png"),
    capital_kr: "반줄",
    capital_en: "Banjul",
    level: 4,
  },
  {
    index: 171,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "마셜 제도",
    name_en: "Marshall Islands",
    image: require("../assets/images/Flag_of_the_Marshall_Islands.png"),
    capital_kr: "마주로",
    capital_en: "Majuro",
    level: 4,
  },
  {
    index: 172,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "네덜란드",
    name_en: "Netherlands",
    image: require("../assets/images/Flag_of_the_Netherlands.png"),
    capital_kr: "암스테르담",
    capital_en: "Amsterdam",
    level: 2,
  },
  {
    index: 173,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "중국",
    name_en: "China",
    image: require("../assets/images/Flag_of_the_People's_Republic_of_China.png"),
    capital_kr: "베이징",
    capital_en: "Beijing",
    level: 1,
  },
  {
    index: 174,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "필리핀",
    name_en: "Philippines",
    image: require("../assets/images/Flag_of_the_Philippines.png"),
    capital_kr: "마닐라",
    capital_en: "Manila",
    level: 2,
  },
  {
    index: 175,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "콩고 공화국",
    name_en: "the Republic of the Congo",
    image: require("../assets/images/Flag_of_the_Republic_of_the_Congo.png"),
    capital_kr: "브라자빌",
    capital_en: "Brazzaville",
    level: 4,
  },
  {
    index: 176,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "솔로몬 제도",
    name_en: "Solomon Islands",
    image: require("../assets/images/Flag_of_the_Solomon_Islands.png"),
    capital_kr: "호니아라",
    capital_en: "Honiara",
    level: 4,
  },
  {
    index: 177,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아랍에미리트",
    name_en: "Arab Emirates",
    image: require("../assets/images/Flag_of_the_United_Arab_Emirates.png"),
    capital_kr: "아부다비",
    capital_en: "Abu Dhabi",
    level: 3,
  },
  {
    index: 178,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "영국",
    name_en: "United Kingdom",
    image: require("../assets/images/Flag_of_the_United_Kingdom.png"),
    capital_kr: "런던",
    capital_en: "London",
    level: 1,
  },
  {
    index: 179,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "미국",
    name_en: "United States",
    image: require("../assets/images/Flag_of_the_United_States.png"),
    capital_kr: "워싱턴 D.C.",
    capital_en: "Washington",
    level: 1,
  },
  {
    index: 180,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "토고",
    name_en: "Togo",
    image: require("../assets/images/Flag_of_Togo.png"),
    capital_kr: "로메",
    capital_en: "Lome",
    level: 3,
  },
  {
    index: 181,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "통가",
    name_en: "Tonga",
    image: require("../assets/images/Flag_of_Tonga.png"),
    capital_kr: "누쿠알로파",
    capital_en: "Nukualofa",
    level: 2,
  },
  {
    index: 182,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "트리니다드 토바고",
    name_en: "Trinidad and Tobago",
    image: require("../assets/images/Flag_of_Trinidad_and_Tobago.png"),
    capital_kr: "포트오브스페인",
    capital_en: "Port-of-Spain",
    level: 2,
  },
  {
    index: 183,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "튀니지",
    name_en: "Tunisia",
    image: require("../assets/images/Flag_of_Tunisia.png"),
    capital_kr: "튀니스",
    capital_en: "Tunis",
    level: 2,
  },
  {
    index: 184,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "터키",
    name_en: "Turkey",
    image: require("../assets/images/Flag_of_Turkey.png"),
    capital_kr: "앙카라",
    capital_en: "Ankara",
    level: 2,
  },
  {
    index: 185,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "투르크메니스탄",
    name_en: "Turkmenistan",
    image: require("../assets/images/Flag_of_Turkmenistan.png"),
    capital_kr: "아슈하바트",
    capital_en: "Ashgabat",
    level: 4,
  },
  {
    index: 186,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "투발루",
    name_en: "Tuvalu",
    image: require("../assets/images/Flag_of_Tuvalu.png"),
    capital_kr: "푸나푸티",
    capital_en: "Funafuti",
    level: 4,
  },
  {
    index: 187,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "우간다",
    name_en: "Uganda",
    image: require("../assets/images/Flag_of_Uganda.png"),
    capital_kr: "캄팔라",
    capital_en: "Kampala",
    level: 4,
  },
  {
    index: 188,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "우크라이나",
    name_en: "Ukraine",
    image: require("../assets/images/Flag_of_Ukraine.png"),
    capital_kr: "키예프",
    capital_en: "Kiev",
    level: 1,
  },
  {
    index: 189,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "우루과이",
    name_en: "Uruguay",
    image: require("../assets/images/Flag_of_Uruguay.png"),
    capital_kr: "몬테비데오",
    capital_en: "Montevideo",
    level: 3,
  },
  {
    index: 190,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "우즈베키스탄",
    name_en: "Uzbekistan",
    image: require("../assets/images/Flag_of_Uzbekistan.png"),
    capital_kr: "타슈켄트",
    capital_en: "Tashkent",
    level: 3,
  },
  {
    index: 191,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "바누아투",
    name_en: "Vanuatu",
    image: require("../assets/images/Flag_of_Vanuatu.png"),
    capital_kr: "빌라",
    capital_en: "Vila",
    level: 4,
  },
  {
    index: 192,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "베네수엘라",
    name_en: "Venezuela",
    image: require("../assets/images/Flag_of_Venezuela.png"),
    capital_kr: "카라카스",
    capital_en: "Caracas",
    level: 3,
  },
  {
    index: 193,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "베트남",
    name_en: "Vietnam",
    image: require("../assets/images/Flag_of_Vietnam.png"),
    capital_kr: "하노이",
    capital_en: "Hanoi",
    level: 1,
  },
  {
    index: 194,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "예멘",
    name_en: "Yemen",
    image: require("../assets/images/Flag_of_Yemen.png"),
    capital_kr: "사나",
    capital_en: "Sanaa",
    level: 2,
  },
  {
    index: 195,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "잠비아",
    name_en: "Zambia",
    image: require("../assets/images/Flag_of_Zambia.png"),
    capital_kr: "루사카",
    capital_en: "Lusaka",
    level: 4,
  },
  {
    index: 196,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "짐바브웨",
    name_en: "Zimbabwe",
    image: require("../assets/images/Flag_of_Zimbabwe.png"),
    capital_kr: "하라레",
    capital_en: "Harare",
    level: 4,
  },
];
