export const CONTINENT = {
  ASIA: "Asia",
  AFRICA: "Africa",
  AMERICA: "America",
  EUROPE: "Europe",
  OCEANIA: "Oceania",
};

export const CONTINENT_DETAIL = {
  SOUTH_ASIA: "South Asia",
  EAST_ASIA: "East Asia",
  SOUTHEAST_ASIA: "Southeast Asia",
  NORTH_ASIA: "North Asia",
  WEST_ASIA: "West Asia",
  CENTRAL_ASIA: "Central Asia",
  NORTH_EUROPE: "North Europe",
  WEST_EUROPE: "West Europe",
  EAST_EUROPE: "East Europe",
  SOUTH_EUROPE: "South Europe",
  CENTRAL_EUROPE: "Central Europe",
  NORTH_AMERICA: "North America",
  CENTRAL_AMERICA: "Central America",
  SOUTH_AMERICA: "South America",
  NORTH_AFRICA: "North Africa",
  WEST_AFRICA: "West Africa",
  EAST_AFRICA: "East Africa",
  SOUTH_AFRICA: "South Africa",
  CENTRAL_AFRICA: "Central Africa",
  AUSTRALASIA: "Australasia",
  MELANESIA: "Melanesia",
  MICRONESIA: "Micronesia",
  POLYNESIA: "Polynesia",
};

export const FLAGS = [
  {
    index: 0,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "아프가니스탄",
    name_en: "Afghanistan",
    image: require("../assets/images/Flag_of_Afghanistan.png"),
    level: 3,
  },
  {
    index: 1,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "알바니아",
    name_en: "Albania",
    image: require("../assets/images/Flag_of_Albania.png"),
    level: 4,
  },
  {
    index: 2,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "알제리",
    name_en: "Algeria",
    image: require("../assets/images/Flag_of_Algeria.png"),
    level: 3,
  },
  {
    index: 3,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "안도라",
    name_en: "Andorra",
    image: require("../assets/images/Flag_of_Andorra.png"),
    level: 3,
  },
  {
    index: 4,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "앙골라",
    name_en: "Angola",
    image: require("../assets/images/Flag_of_Angola.png"),
    level: 3,
  },
  {
    index: 5,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "앤티가 바부다",
    name_en: "Antigua and Barbuda",
    image: require("../assets/images/Flag_of_Antigua_and_Barbuda.png"),
    level: 3,
  },
  {
    index: 6,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "아르헨티나",
    name_en: "Argentina",
    image: require("../assets/images/Flag_of_Argentina.png"),
    level: 2,
  },
  {
    index: 7,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아르메니아",
    name_en: "Armenia",
    image: require("../assets/images/Flag_of_Armenia.png"),
    level: 3,
  },
  {
    index: 8,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.AUSTRALASIA,
    name_kr: "오스트레일리아",
    name_en: "Australia",
    image: require("../assets/images/Flag_of_Australia.png"),
    level: 1,
  },
  {
    index: 9,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "오스트리아",
    name_en: "Austria",
    image: require("../assets/images/Flag_of_Austria.png"),
    level: 2,
  },
  {
    index: 10,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아제르바이잔",
    name_en: "Azerbaijan",
    image: require("../assets/images/Flag_of_Azerbaijan.png"),
    level: 3,
  },
  {
    index: 11,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "바레인",
    name_en: "Bahrain",
    image: require("../assets/images/Flag_of_Bahrain.png"),
    level: 2,
  },
  {
    index: 12,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "방글라데시",
    name_en: "Bangladesh",
    image: require("../assets/images/Flag_of_Bangladesh.png"),
    level: 2,
  },
  {
    index: 13,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "바베이도스",
    name_en: "Barbados",
    image: require("../assets/images/Flag_of_Barbados.png"),
    level: 3,
  },
  {
    index: 14,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "벨라루스",
    name_en: "Belarus",
    image: require("../assets/images/Flag_of_Belarus.png"),
    level: 3,
  },
  {
    index: 15,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "벨기에",
    name_en: "Belgium",
    image: require("../assets/images/Flag_of_Belgium.png"),
    level: 1,
  },
  {
    index: 16,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "벨리즈",
    name_en: "Belize",
    image: require("../assets/images/Flag_of_Belize.png"),
    level: 3,
  },
  {
    index: 17,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "베냉",
    name_en: "Benin",
    image: require("../assets/images/Flag_of_Benin.png"),
    level: 2,
  },
  {
    index: 18,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "부탄",
    name_en: "Bhutan",
    image: require("../assets/images/Flag_of_Bhutan.png"),
    level: 3,
  },
  {
    index: 19,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "볼리비아",
    name_en: "Bolivia",
    image: require("../assets/images/Flag_of_Bolivia.png"),
    level: 2,
  },
  {
    index: 20,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "보스니아 헤르체고비나",
    name_en: "Bosnia and Herzegovina",
    image: require("../assets/images/Flag_of_Bosnia_and_Herzegovina.png"),
    level: 4,
  },
  {
    index: 21,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "보츠와나",
    name_en: "Botswana",
    image: require("../assets/images/Flag_of_Botswana.png"),
    level: 2,
  },
  {
    index: 22,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "브라질",
    name_en: "Brazil",
    image: require("../assets/images/Flag_of_Brazil.png"),
    level: 1,
  },
  {
    index: 23,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "브루나이",
    name_en: "Brunei",
    image: require("../assets/images/Flag_of_Brunei.png"),
    level: 4,
  },
  {
    index: 24,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "불가리아",
    name_en: "Bulgaria",
    image: require("../assets/images/Flag_of_Bulgaria.png"),
    level: 2,
  },
  {
    index: 25,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "부르키나파소",
    name_en: "Burkina Faso",
    image: require("../assets/images/Flag_of_Burkina_Faso.png"),
    level: 2,
  },
  {
    index: 26,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "부룬디",
    name_en: "Burundi",
    image: require("../assets/images/Flag_of_Burundi.png"),
    level: 3,
  },
  {
    index: 27,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "캄보디아",
    name_en: "Cambodia",
    image: require("../assets/images/Flag_of_Cambodia.png"),
    level: 2,
  },
  {
    index: 28,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "카메룬",
    name_en: "Cameroon",
    image: require("../assets/images/Flag_of_Cameroon.png"),
    level: 2,
  },
  {
    index: 29,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "캐나다",
    name_en: "Canada",
    image: require("../assets/images/Flag_of_Canada.png"),
    level: 1,
  },
  {
    index: 30,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "카보베르데",
    name_en: "Cape Verde",
    image: require("../assets/images/Flag_of_Cape_Verde.png"),
    level: 4,
  },
  {
    index: 31,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "차드",
    name_en: "Chad",
    image: require("../assets/images/Flag_of_Chad.png"),
    level: 4,
  },
  {
    index: 32,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "칠레",
    name_en: "Chile",
    image: require("../assets/images/Flag_of_Chile.png"),
    level: 2,
  },
  {
    index: 33,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "콜롬비아",
    name_en: "Colombia",
    image: require("../assets/images/Flag_of_Colombia.png"),
    level: 3,
  },
  {
    index: 34,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "코스타리카",
    name_en: "Costarica",
    image: require("../assets/images/Flag_of_Costarica.png"),
    level: 3,
  },
  {
    index: 35,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "코트디부아르",
    name_en: "Côte_d'Ivoire",
    image: require("../assets/images/Flag_of_CotedIvoire.png"),
    level: 2,
  },
  {
    index: 36,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "크로아티아",
    name_en: "Croatia",
    image: require("../assets/images/Flag_of_Croatia.png"),
    level: 4,
  },
  {
    index: 37,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "쿠바",
    name_en: "Cuba",
    image: require("../assets/images/Flag_of_Cuba.png"),
    level: 2,
  },
  {
    index: 38,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "키프로스",
    name_en: "Cyprus",
    image: require("../assets/images/Flag_of_Cyprus.png"),
    level: 4,
  },
  {
    index: 39,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "덴마크",
    name_en: "Denmark",
    image: require("../assets/images/Flag_of_Denmark.png"),
    level: 1,
  },
  {
    index: 40,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "지부티",
    name_en: "Djibouti",
    image: require("../assets/images/Flag_of_Djibouti.png"),
    level: 2,
  },
  {
    index: 41,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "도미니카 연방",
    name_en: "Dominica",
    image: require("../assets/images/Flag_of_Dominica.png"),
    level: 4,
  },
  {
    index: 42,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "동티모르",
    name_en: "East Timor",
    image: require("../assets/images/Flag_of_East_Timor.png"),
    level: 2,
  },
  {
    index: 43,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "에콰도르",
    name_en: "Ecuador",
    image: require("../assets/images/Flag_of_Ecuador.png"),
    level: 2,
  },
  {
    index: 44,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "이집트",
    name_en: "Egypt",
    image: require("../assets/images/Flag_of_Egypt.png"),
    level: 1,
  },
  {
    index: 45,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "엘살바도르",
    name_en: "El Salvador",
    image: require("../assets/images/Flag_of_El_Salvador.png"),
    level: 2,
  },
  {
    index: 46,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "잉글랜드",
    name_en: "England",
    image: require("../assets/images/Flag_of_England.png"),
    level: 1,
  },
  {
    index: 47,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "적도 기니",
    name_en: "Equatorial Guinea",
    image: require("../assets/images/Flag_of_Equatorial_Guinea.png"),
    level: 4,
  },
  {
    index: 48,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "에리트레아",
    name_en: "Eritrea",
    image: require("../assets/images/Flag_of_Eritrea.png"),
    level: 3,
  },
  {
    index: 49,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "에스토니아",
    name_en: "Estonia",
    image: require("../assets/images/Flag_of_Estonia.png"),
    level: 3,
  },
  {
    index: 50,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "에스와티니",
    name_en: "Eswatini",
    image: require("../assets/images/Flag_of_Eswatini.png"),
    level: 4,
  },
  {
    index: 51,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "에티오피아",
    name_en: "Ethiopia",
    image: require("../assets/images/Flag_of_Ethiopia.png"),
    level: 4,
  },
  {
    index: 52,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "피지",
    name_en: "Fiji",
    image: require("../assets/images/Flag_of_Fiji.png"),
    level: 4,
  },
  {
    index: 53,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "핀란드",
    name_en: "Finland",
    image: require("../assets/images/Flag_of_Finland.png"),
    level: 2,
  },
  {
    index: 54,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "프랑스",
    name_en: "France",
    image: require("../assets/images/Flag_of_France.png"),
    level: 1,
  },
  {
    index: 55,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "가봉",
    name_en: "Gabon",
    image: require("../assets/images/Flag_of_Gabon.png"),
    level: 2,
  },
  {
    index: 56,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "조지아",
    name_en: "Georgia",
    image: require("../assets/images/Flag_of_Georgia.png"),
    level: 4,
  },
  {
    index: 57,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "독일",
    name_en: "Germany",
    image: require("../assets/images/Flag_of_Germany.png"),
    level: 1,
  },
  {
    index: 58,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "가나",
    name_en: "Ghana",
    image: require("../assets/images/Flag_of_Ghana.png"),
    level: 2,
  },
  {
    index: 59,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "그리스",
    name_en: "Greece",
    image: require("../assets/images/Flag_of_Greece.png"),
    level: 1,
  },
  {
    index: 60,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "그레나다",
    name_en: "Grenada",
    image: require("../assets/images/Flag_of_Grenada.png"),
    level: 4,
  },
  {
    index: 61,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "과테말라",
    name_en: "Guatemala",
    image: require("../assets/images/Flag_of_Guatemala.png"),
    level: 2,
  },
  {
    index: 62,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "기니비사우",
    name_en: "Guinea Bissau",
    image: require("../assets/images/Flag_of_Guinea-Bissau.png"),
    level: 4,
  },
  {
    index: 63,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "기니",
    name_en: "Guinea",
    image: require("../assets/images/Flag_of_Guinea.png"),
    level: 2,
  },
  {
    index: 64,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "가이아나",
    name_en: "Guyana",
    image: require("../assets/images/Flag_of_Guyana.png"),
    level: 4,
  },
  {
    index: 65,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "아이티",
    name_en: "Haiti",
    image: require("../assets/images/Flag_of_Haiti.png"),
    level: 4,
  },
  {
    index: 66,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "온두라스",
    name_en: "Honduras",
    image: require("../assets/images/Flag_of_Honduras.png"),
    level: 3,
  },
  {
    index: 67,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "홍콩",
    name_en: "Hong Kong",
    image: require("../assets/images/Flag_of_Hong_Kong.png"),
    level: 2,
  },
  {
    index: 68,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "헝가리",
    name_en: "Hungary",
    image: require("../assets/images/Flag_of_Hungary.png"),
    level: 2,
  },
  {
    index: 69,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "아이슬란드",
    name_en: "Iceland",
    image: require("../assets/images/Flag_of_Iceland.png"),
    level: 2,
  },
  {
    index: 70,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "인도",
    name_en: "India",
    image: require("../assets/images/Flag_of_India.png"),
    level: 2,
  },
  {
    index: 71,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "인도네시아",
    name_en: "Indonesia",
    image: require("../assets/images/Flag_of_Indonesia.png"),
    level: 1,
  },
  {
    index: 72,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이란",
    name_en: "Iran",
    image: require("../assets/images/Flag_of_Iran.png"),
    level: 3,
  },
  {
    index: 73,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이라크",
    name_en: "Iraq",
    image: require("../assets/images/Flag_of_Iraq.png"),
    level: 2,
  },
  {
    index: 74,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "아일랜드",
    name_en: "Ireland",
    image: require("../assets/images/Flag_of_Ireland.png"),
    level: 2,
  },
  {
    index: 75,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "이스라엘",
    name_en: "Israel",
    image: require("../assets/images/Flag_of_Israel.png"),
    level: 3,
  },
  {
    index: 76,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "이탈리아",
    name_en: "Italy",
    image: require("../assets/images/Flag_of_Italy.png"),
    level: 1,
  },
  {
    index: 77,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "자메이카",
    name_en: "Jamaica",
    image: require("../assets/images/Flag_of_Jamaica.png"),
    level: 2,
  },
  {
    index: 78,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "일본",
    name_en: "Japan",
    image: require("../assets/images/Flag_of_Japan.png"),
    level: 1,
  },
  {
    index: 79,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "요르단",
    name_en: "Jordan",
    image: require("../assets/images/Flag_of_Jordan.png"),
    level: 3,
  },
  {
    index: 80,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "카자흐스탄",
    name_en: "Kazakhstan",
    image: require("../assets/images/Flag_of_Kazakhstan.png"),
    level: 4,
  },
  {
    index: 81,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "케냐",
    name_en: "Kenya",
    image: require("../assets/images/Flag_of_Kenya.png"),
    level: 4,
  },
  {
    index: 82,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "키리바시",
    name_en: "Kiribati",
    image: require("../assets/images/Flag_of_Kiribati.png"),
    level: 4,
  },
  {
    index: 83,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "코소보",
    name_en: "Kosovo",
    image: require("../assets/images/Flag_of_Kosovo.png"),
    level: 4,
  },
  {
    index: 84,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "쿠웨이트",
    name_en: "Kuwait",
    image: require("../assets/images/Flag_of_Kuwait.png"),
    level: 3,
  },
  {
    index: 85,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "키르기스스탄",
    name_en: "Kyrgyzstan",
    image: require("../assets/images/Flag_of_Kyrgyzstan.png"),
    level: 4,
  },
  {
    index: 86,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "라오스",
    name_en: "Laos",
    image: require("../assets/images/Flag_of_Laos.png"),
    level: 2,
  },
  {
    index: 87,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "라트비아",
    name_en: "Latvia",
    image: require("../assets/images/Flag_of_Latvia.png"),
    level: 2,
  },
  {
    index: 88,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "레바논",
    name_en: "Lebanon",
    image: require("../assets/images/Flag_of_Lebanon.png"),
    level: 4,
  },
  {
    index: 89,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "레소토",
    name_en: "Lesotho",
    image: require("../assets/images/Flag_of_Lesotho.png"),
    level: 4,
  },
  {
    index: 90,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "라이베리아",
    name_en: "Liberia",
    image: require("../assets/images/Flag_of_Liberia.png"),
    level: 3,
  },
  {
    index: 91,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "리비아",
    name_en: "Libya",
    image: require("../assets/images/Flag_of_Libya.png"),
    level: 3,
  },
  {
    index: 92,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "리히텐슈타인",
    name_en: "Liechtenstein",
    image: require("../assets/images/Flag_of_Liechtenstein.png"),
    level: 3,
  },
  {
    index: 93,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "리투아니아",
    name_en: "Lithuania",
    image: require("../assets/images/Flag_of_Lithuania.png"),
    level: 2,
  },
  {
    index: 94,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "룩셈부르크",
    name_en: "Luxembourg",
    image: require("../assets/images/Flag_of_Luxembourg.png"),
    level: 2,
  },
  {
    index: 95,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "마다가스카르",
    name_en: "Madagascar",
    image: require("../assets/images/Flag_of_Madagascar.png"),
    level: 2,
  },
  {
    index: 96,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "말라위",
    name_en: "Malawi",
    image: require("../assets/images/Flag_of_Malawi.png"),
    level: 3,
  },
  {
    index: 97,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "말레이시아",
    name_en: "Malaysia",
    image: require("../assets/images/Flag_of_Malaysia.png"),
    level: 2,
  },
  {
    index: 98,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "몰디브",
    name_en: "Maldives",
    image: require("../assets/images/Flag_of_Maldives.png"),
    level: 4,
  },
  {
    index: 99,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "말리",
    name_en: "Mali",
    image: require("../assets/images/Flag_of_Mali.png"),
    level: 2,
  },
  {
    index: 100,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "몰타",
    name_en: "Malta",
    image: require("../assets/images/Flag_of_Malta.png"),
    level: 2,
  },
  {
    index: 101,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "모리타니",
    name_en: "Mauritania",
    image: require("../assets/images/Flag_of_Mauritania.png"),
    level: 4,
  },
  {
    index: 102,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "모리셔스",
    name_en: "Mauritius",
    image: require("../assets/images/Flag_of_Mauritius.png"),
    level: 3,
  },
  {
    index: 103,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "멕시코",
    name_en: "Mexico",
    image: require("../assets/images/Flag_of_Mexico.png"),
    level: 1,
  },
  {
    index: 104,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "몰도바",
    name_en: "Moldova",
    image: require("../assets/images/Flag_of_Moldova.png"),
    level: 3,
  },
  {
    index: 105,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "모나코",
    name_en: "Monaco",
    image: require("../assets/images/Flag_of_Monaco.png"),
    level: 2,
  },
  {
    index: 106,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "몽골",
    name_en: "Mongolia",
    image: require("../assets/images/Flag_of_Mongolia.png"),
    level: 4,
  },
  {
    index: 107,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "몬테네그로",
    name_en: "Montenegro",
    image: require("../assets/images/Flag_of_Montenegro.png"),
    level: 4,
  },
  {
    index: 108,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "모로코",
    name_en: "Morocco",
    image: require("../assets/images/Flag_of_Morocco.png"),
    level: 3,
  },
  {
    index: 109,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "모잠비크",
    name_en: "Mozambique",
    image: require("../assets/images/Flag_of_Mozambique.png"),
    level: 4,
  },
  {
    index: 110,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "미얀마",
    name_en: "Myanmar",
    image: require("../assets/images/Flag_of_Myanmar.png"),
    level: 3,
  },
  {
    index: 111,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "나미비아",
    name_en: "Namibia",
    image: require("../assets/images/Flag_of_Namibia.png"),
    level: 4,
  },
  {
    index: 112,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "나우루",
    name_en: "Nauru",
    image: require("../assets/images/Flag_of_Nauru.png"),
    level: 4,
  },
  {
    index: 113,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "네팔",
    name_en: "Nepal",
    image: require("../assets/images/Flag_of_Nepal.png"),
    level: 4,
  },
  {
    index: 114,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.AUSTRALASIA,
    name_kr: "뉴질랜드",
    name_en: "New Zealand",
    image: require("../assets/images/Flag_of_New_Zealand.png"),
    level: 1,
  },
  {
    index: 115,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "니제르",
    name_en: "Niger",
    image: require("../assets/images/Flag_of_Niger.png"),
    level: 3,
  },
  {
    index: 116,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "나이지리아",
    name_en: "Nigeria",
    image: require("../assets/images/Flag_of_Nigeria.png"),
    level: 2,
  },
  {
    index: 117,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "조선민주주의인민공화국",
    name_en: "North Korea",
    image: require("../assets/images/Flag_of_North_Korea.png"),
    level: 1,
  },
  {
    index: 118,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "북마케도니아",
    name_en: "North Macedonia",
    image: require("../assets/images/Flag_of_North_Macedonia.png"),
    level: 4,
  },
  {
    index: 119,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "노르웨이",
    name_en: "Norway",
    image: require("../assets/images/Flag_of_Norway.png"),
    level: 2,
  },
  {
    index: 120,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "오만",
    name_en: "Oman",
    image: require("../assets/images/Flag_of_Oman.png"),
    level: 4,
  },
  {
    index: 121,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "파키스탄",
    name_en: "Pakistan",
    image: require("../assets/images/Flag_of_Pakistan.png"),
    level: 2,
  },
  {
    index: 122,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "팔라우",
    name_en: "Palau",
    image: require("../assets/images/Flag_of_Palau.png"),
    level: 1,
  },
  {
    index: 123,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "팔레스타인",
    name_en: "Palestine",
    image: require("../assets/images/Flag_of_Palestine.png"),
    level: 3,
  },
  {
    index: 124,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AMERICA,
    name_kr: "파나마",
    name_en: "Panama",
    image: require("../assets/images/Flag_of_Panama.png"),
    level: 4,
  },
  {
    index: 125,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "파푸아뉴기니",
    name_en: "Papua New Guinea",
    image: require("../assets/images/Flag_of_Papua_New_Guinea.png"),
    level: 4,
  },
  {
    index: 126,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "파라과이",
    name_en: "Paraguay",
    image: require("../assets/images/Flag_of_Paraguay.png"),
    level: 3,
  },
  {
    index: 127,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "페루",
    name_en: "Peru",
    image: require("../assets/images/Flag_of_Peru.png"),
    level: 3,
  },
  {
    index: 128,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "폴란드",
    name_en: "Poland",
    image: require("../assets/images/Flag_of_Poland.png"),
    level: 1,
  },
  {
    index: 129,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "포르투갈",
    name_en: "Portugal",
    image: require("../assets/images/Flag_of_Portugal.png"),
    level: 3,
  },
  {
    index: 130,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "카타르",
    name_en: "Qatar",
    image: require("../assets/images/Flag_of_Qatar.png"),
    level: 1,
  },
  {
    index: 131,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "루마니아",
    name_en: "Romania",
    image: require("../assets/images/Flag_of_Romania.png"),
    level: 2,
  },
  {
    index: 132,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "러시아",
    name_en: "Russia",
    image: require("../assets/images/Flag_of_Russia.png"),
    level: 2,
  },
  {
    index: 133,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "르완다",
    name_en: "Rwanda",
    image: require("../assets/images/Flag_of_Rwanda.png"),
    level: 3,
  },
  {
    index: 134,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트키츠 네비스",
    name_en: "Saint Kitts and Nevis",
    image: require("../assets/images/Flag_of_Saint_Kitts_and_Nevis.png"),
    level: 4,
  },
  {
    index: 135,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트루시아",
    name_en: "Saint Kitts and Nevis",
    image: require("../assets/images/Flag_of_Saint_Lucia.png"),
    level: 2,
  },
  {
    index: 136,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "세인트빈센트 그레나딘",
    name_en: "Saint Vincent and the Grenadines",
    image: require("../assets/images/Flag_of_Saint_Vincent_and_the_Grenadines.png"),
    level: 3,
  },
  {
    index: 137,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "사모아",
    name_en: "Samoa",
    image: require("../assets/images/Flag_of_Samoa.png"),
    level: 2,
  },
  {
    index: 138,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "사모아",
    name_en: "San Marino",
    image: require("../assets/images/Flag_of_San_Marino.png"),
    level: 4,
  },
  {
    index: 139,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "상투메 프린시페",
    name_en: "Sao Tome and Principe",
    image: require("../assets/images/Flag_of_Sao_Tome_and_Principe.png"),
    level: 3,
  },
  {
    index: 140,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "사우디아라비아",
    name_en: "Saudi Arabia",
    image: require("../assets/images/Flag_of_Saudi_Arabia.png"),
    level: 2,
  },
  {
    index: 141,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "스코틀랜드",
    name_en: "Scotland",
    image: require("../assets/images/Flag_of_Scotland.png"),
    level: 3,
  },
  {
    index: 142,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "세네갈",
    name_en: "Senegal",
    image: require("../assets/images/Flag_of_Senegal.png"),
    level: 3,
  },
  {
    index: 143,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "세르비아",
    name_en: "Serbia",
    image: require("../assets/images/Flag_of_Serbia.png"),
    level: 4,
  },
  {
    index: 144,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "세이셸",
    name_en: "Seychelles",
    image: require("../assets/images/Flag_of_Seychelles.png"),
    level: 4,
  },
  {
    index: 145,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "시에라리온",
    name_en: "Sierra Leone",
    image: require("../assets/images/Flag_of_Sierra_Leone.png"),
    level: 3,
  },
  {
    index: 146,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "싱가포르",
    name_en: "Singapore",
    image: require("../assets/images/Flag_of_Singapore.png"),
    level: 2,
  },
  {
    index: 147,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "슬로바키아",
    name_en: "Slovakia",
    image: require("../assets/images/Flag_of_Slovakia.png"),
    level: 3,
  },
  {
    index: 148,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "소말리아",
    name_en: "Somalia",
    image: require("../assets/images/Flag_of_Somalia.png"),
    level: 1,
  },
  {
    index: 149,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "남아프리카 공화국",
    name_en: "South Africa",
    image: require("../assets/images/Flag_of_South_Africa.png"),
    level: 4,
  },
  {
    index: 150,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "대한민국",
    name_en: "South Korea",
    image: require("../assets/images/Flag_of_South_Korea.png"),
    level: 1,
  },
  {
    index: 151,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "남수단",
    name_en: "South Sudan",
    image: require("../assets/images/Flag_of_South_Sudan.png"),
    level: 4,
  },
  {
    index: 152,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.SOUTH_EUROPE,
    name_kr: "스페인",
    name_en: "Spain",
    image: require("../assets/images/Flag_of_Spain.png"),
    level: 2,
  },
  {
    index: 153,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTH_ASIA,
    name_kr: "스리랑카",
    name_en: "Sri Lanka",
    image: require("../assets/images/Flag_of_Sri_Lanka.png"),
    level: 4,
  },
  {
    index: 154,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "수단",
    name_en: "Sudan",
    image: require("../assets/images/Flag_of_Sudan.png"),
    level: 4,
  },
  {
    index: 155,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "수리남",
    name_en: "Suriname",
    image: require("../assets/images/Flag_of_Suriname.png"),
    level: 3,
  },
  {
    index: 156,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.NORTH_EUROPE,
    name_kr: "스웨덴",
    name_en: "Sweden",
    image: require("../assets/images/Flag_of_Sweden.png"),
    level: 2,
  },
  {
    index: 157,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "스위스",
    name_en: "Switzerland",
    image: require("../assets/images/Flag_of_Switzerland.png"),
    level: 1,
  },
  {
    index: 158,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "시리아",
    name_en: "Syria",
    image: require("../assets/images/Flag_of_Syria.png"),
    level: 3,
  },
  {
    index: 159,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "타지키스탄",
    name_en: "Tajikistan",
    image: require("../assets/images/Flag_of_Tajikistan.png"),
    level: 3,
  },
  {
    index: 160,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "탄자니아",
    name_en: "Tanzania",
    image: require("../assets/images/Flag_of_Tanzania.png"),
    level: 4,
  },
  {
    index: 161,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "태국",
    name_en: "Thailand",
    image: require("../assets/images/Flag_of_Thailand.png"),
    level: 2,
  },
  {
    index: 162,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아시리아",
    name_en: "Assyrians",
    image: require("../assets/images/Flag_of_the_Assyrians.png"),
    level: 4,
  },
  {
    index: 163,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "바하마",
    name_en: "Bahamas",
    image: require("../assets/images/Flag_of_the_Bahamas.png"),
    level: 3,
  },
  {
    index: 164,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "중앙아프리카 공화국",
    name_en: "Central African Republic",
    image: require("../assets/images/Flag_of_the_Central_African_Republic.png"),
    level: 4,
  },
  {
    index: 165,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "코모로",
    name_en: "Comoros",
    image: require("../assets/images/Flag_of_the_Comoros.png"),
    level: 4,
  },
  {
    index: 166,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.CENTRAL_EUROPE,
    name_kr: "체코",
    name_en: "Czech Republic",
    image: require("../assets/images/Flag_of_the_Czech_Republic.png"),
    level: 2,
  },
  {
    index: 167,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "콩고 민주 공화국",
    name_en: "Democratic Republic of the Congo",
    image: require("../assets/images/Flag_of_the_Democratic_Republic_of_the_Congo.png"),
    level: 4,
  },
  {
    index: 168,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "도미니카 공화국",
    name_en: "Dominican Republic",
    image: require("../assets/images/Flag_of_the_Dominican_Republic.png"),
    level: 4,
  },
  {
    index: 169,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "미크로네시아 연방",
    name_en: "Federated States of Micronesia",
    image: require("../assets/images/Flag_of_the_Federated_States_of_Micronesia.png"),
    level: 4,
  },
  {
    index: 170,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "감비아",
    name_en: "Gambia",
    image: require("../assets/images/Flag_of_The_Gambia.png"),
    level: 4,
  },
  {
    index: 171,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MICRONESIA,
    name_kr: "마셜 제도",
    name_en: "Marshall Islands",
    image: require("../assets/images/Flag_of_the_Marshall_Islands.png"),
    level: 4,
  },
  {
    index: 172,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "네덜란드",
    name_en: "Netherlands",
    image: require("../assets/images/Flag_of_the_Netherlands.png"),
    level: 2,
  },
  {
    index: 173,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.EAST_ASIA,
    name_kr: "중국",
    name_en: "China",
    image: require("../assets/images/Flag_of_the_People's_Republic_of_China.png"),
    level: 1,
  },
  {
    index: 174,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "필리핀",
    name_en: "Philippines",
    image: require("../assets/images/Flag_of_the_Philippines.png"),
    level: 2,
  },
  {
    index: 175,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_AFRICA,
    name_kr: "콩고 공화국",
    name_en: "the Republic of the Congo",
    image: require("../assets/images/Flag_of_the_Republic_of_the_Congo.png"),
    level: 4,
  },
  {
    index: 176,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "솔로몬 제도",
    name_en: "Solomon Islands",
    image: require("../assets/images/Flag_of_the_Solomon_Islands.png"),
    level: 4,
  },
  {
    index: 177,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "아랍에미리트",
    name_en: "Arab Emirates",
    image: require("../assets/images/Flag_of_the_United_Arab_Emirates.png"),
    level: 3,
  },
  {
    index: 178,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.WEST_EUROPE,
    name_kr: "영국",
    name_en: "United Kingdom",
    image: require("../assets/images/Flag_of_the_United_Kingdom.png"),
    level: 1,
  },
  {
    index: 179,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "미국",
    name_en: "United States",
    image: require("../assets/images/Flag_of_the_United_States.png"),
    level: 1,
  },
  {
    index: 180,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.WEST_AFRICA,
    name_kr: "토고",
    name_en: "Togo",
    image: require("../assets/images/Flag_of_Togo.png"),
    level: 3,
  },
  {
    index: 181,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "통가",
    name_en: "Tonga",
    image: require("../assets/images/Flag_of_Tonga.png"),
    level: 2,
  },
  {
    index: 182,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AMERICA,
    name_kr: "트리니다드 토바고",
    name_en: "Trinidad and Tobago",
    image: require("../assets/images/Flag_of_Trinidad_and_Tobago.png"),
    level: 2,
  },
  {
    index: 183,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.NORTH_AFRICA,
    name_kr: "튀니지",
    name_en: "Tunisia",
    image: require("../assets/images/Flag_of_Tunisia.png"),
    level: 2,
  },
  {
    index: 184,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "터키",
    name_en: "Turkey",
    image: require("../assets/images/Flag_of_Turkey.png"),
    level: 2,
  },
  {
    index: 185,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "투르크메니스탄",
    name_en: "Turkmenistan",
    image: require("../assets/images/Flag_of_Turkmenistan.png"),
    level: 4,
  },
  {
    index: 186,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.POLYNESIA,
    name_kr: "투발루",
    name_en: "Tuvalu",
    image: require("../assets/images/Flag_of_Tuvalu.png"),
    level: 4,
  },
  {
    index: 187,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.EAST_AFRICA,
    name_kr: "우간다",
    name_en: "Uganda",
    image: require("../assets/images/Flag_of_Uganda.png"),
    level: 4,
  },
  {
    index: 188,
    continent: CONTINENT.EUROPE,
    continent_detail: CONTINENT_DETAIL.EAST_EUROPE,
    name_kr: "우크라이나",
    name_en: "Ukraine",
    image: require("../assets/images/Flag_of_Ukraine.png"),
    level: 1,
  },
  {
    index: 189,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "우루과이",
    name_en: "Uruguay",
    image: require("../assets/images/Flag_of_Uruguay.png"),
    level: 3,
  },
  {
    index: 190,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.CENTRAL_ASIA,
    name_kr: "우즈베키스탄",
    name_en: "Uzbekistan",
    image: require("../assets/images/Flag_of_Uzbekistan.png"),
    level: 3,
  },
  {
    index: 191,
    continent: CONTINENT.OCEANIA,
    continent_detail: CONTINENT_DETAIL.MELANESIA,
    name_kr: "바누아투",
    name_en: "Vanuatu",
    image: require("../assets/images/Flag_of_Vanuatu.png"),
    level: 4,
  },
  {
    index: 192,
    continent: CONTINENT.AMERICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AMERICA,
    name_kr: "베네수엘라",
    name_en: "Venezuela",
    image: require("../assets/images/Flag_of_Venezuela.png"),
    level: 3,
  },
  {
    index: 193,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.SOUTHEAST_ASIA,
    name_kr: "베트남",
    name_en: "Vietnam",
    image: require("../assets/images/Flag_of_Vietnam.png"),
    level: 1,
  },
  {
    index: 194,
    continent: CONTINENT.ASIA,
    continent_detail: CONTINENT_DETAIL.WEST_ASIA,
    name_kr: "예멘",
    name_en: "Yemen",
    image: require("../assets/images/Flag_of_Yemen.png"),
    level: 2,
  },
  {
    index: 195,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "잠비아",
    name_en: "Zambia",
    image: require("../assets/images/Flag_of_Zambia.png"),
    level: 4,
  },
  {
    index: 196,
    continent: CONTINENT.AFRICA,
    continent_detail: CONTINENT_DETAIL.SOUTH_AFRICA,
    name_kr: "짐바브웨",
    name_en: "Zimbabwe",
    image: require("../assets/images/Flag_of_Zimbabwe.png"),
    level: 4,
  },
];
